pipeline {
    agent any

    environment {
        PYTHONPATH = 'workspace'
        DB_HOST     = 'host.docker.internal'
        DB_NAME     = 'postgres'
        DB_USER     = 'postgres'
        DB_PASS     = 'mysecretpassword'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('lesson_29') {
                    sh 'pip install --break-system-packages -r requirements.txt || pip install -r requirements.txt'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('lesson_29') {
                    catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                        // Вказуємо точний шлях до pytest всередині Jenkins
                        sh '/var/jenkins_home/.local/bin/pytest -v --alluredir=allure-results'
                    }
                }
            }
        }
    }
}